A **design pattern** is a reusable, battle-tested solution to a commonly occurring problem in software design.

Instead of being a specific piece of code (like a library or a framework) that you can copy and paste directly into your program, a design pattern acts like a **blueprint or a conceptual template**. It describes a structural approach to organizing your classes, objects, and relationships to solve a specific architectural challenge.

---

- **🏗️ The Real-World Analogy**
    - Think of design patterns like architectural blueprints for building houses:
        * If you want to build a kitchen, you don’t reinvent the wheel. You use a standard, proven **pattern**: putting the sink, stove, and refrigerator in a close triangle layout for maximum efficiency.
        * You can build that kitchen out of wood, marble, or steel (different programming languages), and it can be large or small (different applications), but the core *structural pattern* remains identical.

---

- **📑 The Three Main Categories**

- Design patterns were famously cataloged in 1994 by the "Gang of Four" (GoF) and are broken down into three fundamental groups based on their purpose:

- **1. Creational Patterns**
    - These patterns deal with **object creation mechanisms**. They isolate the logic of *how* objects are instantiated, making a system independent of how its components are created and composed.
    * *Example:* **Singleton Pattern** (ensures a class has only one single instance globally, like a database connection pool) or **Factory Pattern**.

- **2. Structural Patterns**
    - These patterns explain how to assemble objects and classes into **larger structures** while keeping these structures flexible and efficient. They focus on how classes inherit from each other and how they interact.
    * *Example:* **Adapter Pattern** (allows two incompatible interfaces to work together, acting like a physical travel plug adapter).

- **3. Behavioral Patterns**
    - These patterns are specifically concerned with **communication between objects**. They define how responsibilities and data flow are distributed across different algorithms and classes.
    * *Example:* **Observer Pattern** (a subscription mechanism where multiple objects are instantly notified of any state changes to the object they are watching, like a YouTube notification system).

---

- **🚀 Why Use Them?**
    * **Don't Reinvent the Wheel:** They are solutions that thousands of developers have already refined through trial and error over decades.
    * **Universal Developer Vocabulary:** If you tell a teammate, *"I used an Observer pattern here,"* everyone instantly understands the data flow architecture without needing to read hundreds of lines of code.
    * **Code Maintainability:** They inherently promote software design best practices, such as loose coupling, encapsulation, and high cohesion, which makes your code significantly easier to scale and debug down the line.

## **Time complexity – The big O notation**

**Big O notation** is a mathematical tool used in computer science to measure the efficiency of an algorithm. Specifically, it answers the question: **How does the execution time (or memory space) of an algorithm scale as the amount of input data grows?**

It doesn’t measure time in seconds, because a fast supercomputer and a slow phone will take different amounts of time to run the same code. Instead, Big O measures the **number of operational steps** the computer must take.

---

- **🏎️ The Core Concept: Growth Rate**
    - Imagine you want to send a file to a friend who lives across town.
        * **Method A (The Internet):** You upload the file to a cloud drive. If the file is small (1 MB), it takes 2 seconds. If the file is massive (1 TB), it might take 20 hours. **The time scales linearly with the size of the file.**
        * **Method B (The Airplane):** You copy the file onto a physical hard drive and mail it via overnight shipping. Whether the file is 1 MB or 1 TB, the package takes exactly 12 hours to arrive. **The time remains constant, regardless of the file size.**

> As the file size grows toward infinity, the physical airplane eventually becomes much faster than the internet connection. That is what Big O analyzes: the behavior of your code when input sizes become very large.

---

- **📈 Common Big O Complexities (Ordered from Fastest to Slowest)**

- **1. Constant Time: $O(1)$**
    - The algorithm takes the exact same number of steps to finish, regardless of how much data you throw at it. This is the gold standard of efficiency.
    * **Code Example:** Looking up an element in an array using its index.
```python
def get_first_item(items):
    return items[0]  # Takes 1 step, whether items has 5 entries or 5 million.
```

- **2. Logarithmic Time: $O(\log n)$**
    - The algorithm cuts the remaining data pool in half with every single step it takes. It is incredibly efficient because even if your dataset doubles in size, the algorithm only needs one extra step to finish.
    * **Code Example:** Binary Search (searching for a name in a physically printed, alphabetized phone book by opening it exactly to the middle page each time).

- **3. Linear Time: $O(n)$**
    - The execution time grows in direct, 1-to-1 proportion with the size of the input data ($n$). If you double the data, you double the steps.
    * **Code Example:** Looping through a collection to find a specific item.
```python
def read_all_items(items):
    for item in items:
        print(item)  # Runs 'n' times for 'n' items.
```

- **4. Linearithmic Time: $O(n \log n)$**
    - Slightly slower than linear time, this usually occurs when you split a problem into smaller halves ($O(\log n)$) and then merge them back together ($O(n)$).
    * **Code Example:** Highly optimized sorting algorithms like Merge Sort or Quick Sort.

- **5. Quadratic Time: $O(n^2)$**
    - The execution time scales proportionally to the *square* of the input size. If your data size doubles ($2$), the execution steps quadruple ($2^2 = 4$). These algorithms scale very poorly and should be avoided for large datasets.
    * **Code Example:** Nested loops traversing the same collection.
```python
def find_duplicate_pairs(items):
    for item_a in items:
        for item_b in items:
            if item_a == item_b:
                print("Match found!")
```

---

- **🔍 The Rules of Big O: Simplifying the Math**

    - When analyzing code to calculate its Big O, you follow two main rules to simplify the final mathematical expression:

- **Rule 1: Drop the Constants**
Big O looks at the overarching *shape* of the growth curve, not micro-optimizations.
If an algorithm takes $2n + 5$ steps, we drop the constant multiplier ($2$) and the flat addition ($5$). The complexity is simplified down to **$O(n)$**.

- **Rule 2: Keep the Dominant Term**
If an algorithm has multiple phases where it does different things, you only care about the part that grows the fastest.
If your code has an $O(n^2)$ phase followed by an $O(n)$ phase, the math is expressed as $O(n^2 + n)$. Because $n^2$ grows so catastrophically faster than $n$ as numbers get massive, the smaller term becomes irrelevant. We simplify it to **$O(n^2)$**.

> Note : The big **O** letter refers to the capital version of the Greek letter **Omicron**, which means **small-o (micron o)**.

- In addition to O, several other characters might pop up in literature. Here’s an overview of the characters used:
    * **Ο Big Omicron:** The upper bound/worst-case scenario.
    * **Ω Big Omega:** The lower bound/best-case scenario.
    * **Θ Big Theta:** The tight bound, which means both O and Ω are identical.

In [5]:
n = 1000
a = list(range(n))
b = dict.fromkeys(range(n))

for i in range(n):
    assert i in a   # take n = 1000 step
    assert i in b   # take  1 step

- **To illustrate O(1), O(n), and O(n\*\*2) functions:**

In [11]:
def o_one(item):
    return 1 # 1 operation so O(1)

def o_n(items):
    total = 0
    # Walks through all items once so O(n)
    for item in items:
        total += item

    return total

def o_n_squared(items):
    total = 0
    # Walks through all items n*n times so O(n**2)
    for a in items:
        for b in items:
            total += a * b
    
    return total

In [12]:
n = 10
items = range(n)

In [13]:
o_one(items)

1

In [14]:
o_n(items)

45

In [15]:
o_n_squared(items)

2025

![Time complexity of slow-growing functions](./Images/Time_complexity_of_slow-growing_functions.png)

![Time complexity of fast-growing functions](./Images/Time_complexity_of_fast-growing_functions.png)

## **Core collections**

### **list – A mutable list of items**

- While Python lists offer maximum efficiency **($O(1)$ constant time)** for common operations like appending items, accessing or setting values by index, and checking the collection's length, they carry hidden performance costs for structural modifications. Specifically, removing an item or inserting one at an arbitrary position degrades to a linear worst-case time complexity of **$O(n)$.** This means that to delete or insert a single element, Python may be forced to sequentially walk through and shift every single item in the entire collection, making these operations significantly slower as the dataset scales.

In [22]:
def remove(collection, item):
    new_collection = []
    found = False

    for element in collection:
        if not found and element == item:
            found = True
            continue
        new_collection.append(element)

    if not found:
        raise ValueError("The Element is not in the list")

    return new_collection


def insert(collection, value, index):
    new_collection = []

    for i, item in enumerate(collection):
        if i == index:
            new_collection.append(value)
        new_collection.append(item)

    return new_collection

In [23]:
items = list(range(10))

items

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
items = remove(items, 5)

items

[0, 1, 2, 3, 4, 6, 7, 8, 9]

In [25]:
items = insert(items, 5, 5)

items

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- When removing or inserting elements at arbitrary positions within a Python list, the engine must sequentially shift all subsequent items in memory to close or open the data gap. While a single modification is negligible, executing multiple in-place removals scales inefficiently due to this continuous data shuffling. To optimize performance on larger datasets, you should choose **$O(1)$** appends over insertions whenever possible. Furthermore, instead of running repetitive **`.remove()`** operations in a loop, utilizing a list comprehension or filter is significantly faster because it evaluates the conditions dynamically and copies the desired elements into a fresh memory layout exactly once.

In [33]:
primes = set((1, 2, 4, 5, 7))
items = list(range(10))

In [34]:
# classic solution
for prime in primes:
    items.remove(prime)

items

[0, 3, 6, 8, 9]

In [35]:
# List Comprehension Solution
items = [i for i in range(10) if i not in primes]

items

[0, 3, 6, 8, 9]

In [ ]:
# # Filter Solution
items = list(range(10))
items = list(filter(lambda item)) 

In [1]:
def in_(items, item):
    for i in items:
        if i == item:
            return True
    return False


def min_(items):
    current_value = items[0]
    for i in items[1:]:
        if current_value > i:
            current_value = i

    return current_value


def max_(items):
    current_value = items[0]
    for i in items[1:]:
        if current_value < i:
            current_value = i

    return current_value

In [2]:
r = range(5)

In [3]:
in_(r, 3)

True

In [4]:
min_(r), max_(r)

(0, 4)

The **`in`** operator in Python illustrates how an algorithm's performance can vary drastically between its best, worst, and average execution paths. In the best-case scenario, the operation achieves a constant time complexity of **$O(1)$** if the target value happens to be the very first item in the list. Conversely, the worst-case scenario escalates to linear time, or **$O(n)$**, because Python must scan the entire collection sequentially if the item is at the very end or missing entirely. While it might seem intuitive to assume an average-case complexity of **$O(n/2)$**, the average-case remains mathematically classified as **$O(n)$** because there is a high statistical probability in real-world applications that the searched item does not exist in the list at all, forcing a complete, front-to-back traversal of the dataset.

### **dict – A map of items**

The dictionary **(`dict`)** is one of Python’s most ubiquitous and fundamental containers, running continuously behind the scenes to manage variable names and scopes via **`local()`** and **`global()`** namespace lookups. It provides exceptionally fast performance, boasting an average-case time complexity of **$O(1)$** constant time for data retrieval, assignment, and deletion. This speed is achieved by passing keys through a hash function to map them onto an internal hash table, which naturally causes elements to appear in a randomized order rather than by sequential input.

> Magic methods such as __hash__ are called either magic methods or dunder methods, where dunder is short for double-underscore.

- However, under rare circumstances, multiple distinct keys can generate the identical hash value, causing a hash collision; in these worst-case scenarios, the operational complexity degrades from **$O(1)$** to a sluggish linear time of **$O(n)$** as Python relies on a secondary search fallback to differentiate the colliding items.

> Since **Python 3.6**, the default dict implementation in **CPython** has changed to a version that is sorted by insertion. Since Python **3.7**, this is guaranteed behavior since other Python versions such as **Jython** and **PyPy** could use different implementations before version **3.7**.

In [14]:
def most_significant(value):
    while value >= 10:
        value //= 10
    return value


def add(collections, key, value):
    index = most_significant(key)
    collections[index].append((key, value))


def contains(collections, key):
    index = most_significant(key)
    for k, v in collections[index]:
        if k == key:
            return True
    return False

In [15]:
# Create the collection of 10 lists
collection = [[], [], [], [], [], [], [], [], [], []]

# Add some items, using key/value pairs
add(collection, 123, 'a')
add(collection, 456, 'b')
add(collection, 789, 'c')
add(collection, 101, 'c')

collection

[[],
 [(123, 'a'), (101, 'c')],
 [],
 [],
 [(456, 'b')],
 [],
 [],
 [(789, 'c')],
 [],
 []]

In [17]:
# Check if the contains works correctly
contains(collection, 123), contains(collection, 1)

(True, False)

- it illustrates a simplified conceptual layout of a Python dictionary, demonstrating how direct array indexing yields an efficient **$O(1)$** constant lookup cost in the general case. However, when multiple distinct keys (such as 123 and 101) map into the exact same index bucket, a hash collision occurs, threatening to degrade the system's runtime performance to a sluggish worst-case linear complexity of **$O(n)$** if all keys converge on a single bucket. To alleviate these collisions and maintain near-constant speeds beyond the standard capabilities of the native **`hash()`** function, the underlying Python **`dict`** architecture utilizes a dynamic probing sequence that automatically shifts conflicting hashes to open slots across the table—a low-level execution logic detailed heavily within the CPython source file **`dictobject.c`**.

> To debug **hash collisions**, you can use the **hash()** function paired with collections. Counter. This will quickly show you where hash collisions occur but it does not take the dict probing sequence into consideration.

Beyond the performance hurdles of hash collisions, deleting items from a Python dictionary introduces a surprising memory behavior: it removes the data references but does not automatically downsize the underlying hash table allocation in system RAM. As a result, subsequent operations like copying or iterating over the entire collection scale relative to the historical maximum capacity of the dictionary (**$O(m)$**, where **$m$** represents the peak allocation size) rather than the current count of active elements **($n$)**. For instance, if you populate a dictionary with 1,000 items and subsequently delete 999 of them, iterating or copying that container will still require a full 1,000-step traversal across the empty memory slots. The only reliable workaround to reclaim this memory and restore operational efficiency is to explicitly recreate the dictionary—forcing a fresh, compacted structure—which occurs automatically during a manual clone operation or occasionally during new insertions if the internal architecture runs out of free tracking slots.

### **set – Like a dict without values**

- A set is a structure that uses the **hash()** function to get a unique collection of values. Internally, it is very similar to a dict, with the same **hash collision** problem, but there are a few handy features of set.

In [24]:
def print_set(expression, set_):
    'Print set as a string sorted by letters'
    print(expression, ''.join(sorted(set_)))

In [30]:
spams = set('spams')

print_set('spams :', spams)
spam

spams : amps


{'a', 'm', 'p', 's'}

In [33]:
eggs = set('eggs')

print_set("eggs :", eggs)
eggs

eggs : egs


{'e', 'g', 's'}

![Set_Operation](./Images/Set_Operation.png)

- In permission architectures, a frequent administrative requirement involves processing mass user modifications—such as adding or removing large blocks of accounts from a specific group simultaneously. Because many permission databases cannot overwrite a group's entire membership roster in a single monolithic query, developers must separate the incoming data stream into two distinct pools: an insertion list for new users and a deletion list for revoked users. This exact structural segregation is where Python's native **`set`** object becomes incredibly useful, allowing you to leverage high-performance mathematical operations like differences and intersections to instantly calculate exactly which users need to be added or removed without writing sluggish, nested loop validations.

In [34]:
current_user = set((
    'a', 'b', 'd'
))

new_user = set((
    'b', 'e', 'd', 'c'
))

to_insert = new_user - current_user
to_remove = current_user - new_user
unchanged = new_user & current_user

to_insert, to_remove, unchanged

({'c', 'e'}, {'a'}, {'b', 'd'})

### **tuple – The immutable list**

In [38]:
spam = 1, 2, 3
eggs = 4, 5, 6

data = dict()

# use a set like a key because they immutability
data[spam] = 'spam'
data[eggs] = 'eggs'

In [36]:
import pprint

In [37]:
pprint.pprint(data)

{(1, 2, 3): 'spam', (4, 5, 6): 'eggs'}


- Tuple support packing and unpacking

In [39]:
a, b = 1, (2, 3)

print('a = ', a)
print('b = ', b)

a =  1
b =  (2, 3)


In [40]:
spam = a, b

spam

(1, (2, 3))

In [41]:
b, a = spam

print('b = ', b)
print('a = ', a)

b =  1
a =  (2, 3)


- In addition to regular **packing and unpacking**, from Python 3 onward, we can actually pack and **unpack** objects with a variable number of items.

In [44]:
a, b, *c = 1, 2, 3, 4, 5, 6

print('a = ', a)
print('b = ', b, type(b))
print('c = ', c, type(c))

a =  1
b =  2 <class 'int'>
c =  [3, 4, 5, 6] <class 'list'>


In [50]:
d, *e = 8, *c

print('d = ', d)
print('e = ', e, type(e))

d =  8
e =  [3, 4, 5, 6] <class 'list'>


## **Pythonic patterns using advanced collections**

### **Smart data storage with type hinting using dataclasses**

**Type hinting** (introduced in Python 3.5) is a formal syntax used to explicitly declare what data type a variable, function argument, or return value is *expected* to be.

By default, Python is a **dynamically typed** language. This means Python figures out data types automatically at runtime, and a variable can change from an integer to a string whenever you want. Type hinting allows you to layer a **statically typed** style on top of Python's dynamic core, giving you the best of both worlds.

---

- **🛠️ The Basic Syntax**
    - Type hints use a colon (`:`) for variables and arguments, and an arrow (`->`) for function return values.

- **Without Type Hints (Pure Dynamic Python)**
    - If you read this code, you have to guess what data types the developer intended to use:
```python
def process_invoice(client, amount, tax_rate):
    total = amount * (1 + tax_rate)
    return f"Invoice for {client}: ${total}"
```

- **With Type Hints (Explicit Intent)**
    - Now, the code documents exactly how it expects to receive and return data:
```python
def process_invoice(client: str, amount: float, tax_rate: float) -> str:
    total = amount * (1 + tax_rate)
    return f"Invoice for {client}: ${total}"
```

---

- **⚠️ The Golden Rule: Python Ignores Type Hints**
    - The most critical concept to understand about type hinting is that **Python completely ignores them at runtime.** Type hints are completely cosmetic to the Python interpreter. If you hint that an argument should be a string (`name: str`), but you accidentally pass an integer (`42`) into the function, Python will not throw an error or crash.
```python
def greet(name: str):
    print(f"Hello, {name}")

# Python runs this perfectly without errors, despite the hint violation!
greet(42)  
```

- **If Python ignores them, why use them?**
    - Type hints are not meant for the Python execution engine; they are built for your **development tools**. They are analyzed *before* your code runs.

---

- **🚀 The Three Main Benefits of Type Hinting**

- **1. Supercharged IDE Autocomplete**
    - When your code editor (like VS Code or PyCharm) knows exactly what data type a variable is, it can provide incredibly accurate auto-completion.
    - If you hint that a parameter is a string (`data: str`), typing `data.` will instantly pop up string-specific methods like `.upper()`, `.split()`, or `.strip()`.

- **2. Catching Bugs Before Runtime (Static Analysis)**
    - Instead of waiting for a user to trigger a crash in production, you can run a **static type checker** like **Mypy**, **Pyright**, or **Ruff**. These tools scan your code file from top to bottom, look at your hints, and warn you about logical type mismatches before a single line of code is executed.
```bash
# Running a type checker in your terminal
$ mypy script.py
script.py:5: error: Argument 1 to "greet" has incompatible type "int"; expected "str"
```

- **3. Clearer Code Documentation**
    - Type hints act as living documentation that never goes out of date. Instead of digging through a function's logic or reading outdated comment blocks to figure out what data formats to pass in, a developer can instantly read the function signature.

---

- **📦 Advanced Hinting Types**
    - Modern Python (3.10+) includes elegant syntax for expressing complex data structures.

- **1. The Union Operator (`|`)**
    - If a variable or argument can legitimately accept more than one data type, you separate the options using the pipe symbol.
```python
# 'user_id' can be an integer or a string
def fetch_profile(user_id: int | str):
    pass
```

- **2. Optional Values (`None`)**
    - If a value is allowed to be missing or defaults to `None`, you express it by joining the expected type with `None`.
```python
# 'middle_name' must be a string, but it is allowed to be None
def create_user(first_name: str, middle_name: str | None = None):
    pass
```

- **3. Complex Collections**
    - You can hint the internal architecture of lists, dictionaries, and tuples to keep your data structures highly organized:
```python
# A list that strictly contains integers
scores: list[int] = [98, 87, 93]

# A dictionary where keys are strings and values are floats
exchange_rates: dict[str, float] = {"USD": 1.0, "EUR": 0.92}
```

In [51]:
import dataclasses

In [52]:
@dataclasses.dataclass
class Sandwish:
    spam: int
    eggs: int = 3

In [53]:
Sandwish(8, 9)

Sandwish(spam=8, eggs=9)

In [54]:
sandwish = Sandwish(8)
sandwish

Sandwish(spam=8, eggs=3)

In [55]:
sandwish.eggs

3

In [56]:
dataclasses.asdict(sandwish)

{'spam': 8, 'eggs': 3}

In [57]:
dataclasses.astuple(sandwish)

(8, 3)

In [58]:
help(dataclasses.dataclass)

Help on function dataclass in module dataclasses:

dataclass(
    cls=None,
    /,
    *,
    init=True,
    repr=True,
    eq=True,
    order=False,
    unsafe_hash=False,
    frozen=False,
    match_args=True,
    kw_only=False,
    slots=False,
    weakref_slot=False
)
    Add dunder methods based on the fields defined in the class.

    Examines PEP 526 __annotations__ to determine fields.

    If init is true, an __init__() method is added to the class. If repr
    is true, a __repr__() method is added. If order is true, rich
    comparison dunder methods are added. If unsafe_hash is true, a
    __hash__() method is added. If frozen is true, fields may not be
    assigned to after instance creation. If match_args is true, the
    __match_args__ tuple is added. If kw_only is true, then by default
    all fields are keyword-only. If slots is true, a new class with a
    __slots__ attribute is returned.



In Python, **dataclasses** (introduced in Python 3.7 via the `dataclasses` module) are a powerful utility designed to drastically reduce the repetitive, boilerplate code needed to create and maintain classes that primarily exist to store data.

Before dataclasses, writing a clean data-holding class required you to manually define structural methods like `__init__()`, `__repr__()`, and `__eq__()`. A dataclass automatically generates these under the hood based on type hints.

---

- **🏎️ The Main Utility: Eliminating Boilerplate**
    - To understand their value, compare how you define a simple `Project` object with and without a dataclass.

- **The Old Way (Standard Class)**
    - Even for a simple class with three attributes, you have to write a wall of repetitive code just to make it behave intuitively:
```python
class ProjectStandard:
    def __init__(self, name: str, budget: int, active: bool):
        self.name = name
        self.budget = budget
        self.active = active

    # Required just so printing the object doesn't look like <__main__.Project object at 0x7f...>
    def __repr__(self):
        return f"ProjectStandard(name={self.name!r}, budget={self.budget}, active={self.active})"

    # Required so project1 == project2 compares data instead of memory addresses
    def __eq__(self, other):
        if not isinstance(other, ProjectStandard):
            return NotImplemented
        return (self.name, self.budget, self.active) == (other.name, other.budget, other.active)
```

- **The New Way (With `@dataclass`)**
    - The `@dataclass` decorator scans your class declaration, reads your type hints, and writes all of those hidden structural dunder methods for you automatically.
```python
from dataclasses import dataclass

@dataclass
class ProjectData:
    name: str
    budget: int
    active: bool
```

> Both classes do the exact same thing, but the dataclass achieves it in a fraction of the lines, making it significantly easier to read, maintain, and scale.

---

- **🛠️ Advanced Superpowers of Dataclasses**
    - Dataclasses aren't just a syntax shortcut; they come packed with configuration flags that solve advanced architectural design challenges out of the box.

- **1. Instant Immutability (`frozen=True`)**
    - If you want to create a read-only data structure that cannot be modified after it is created, you can pass `frozen=True`. This also automatically generates a `__hash__()` method, meaning your data objects can safely be used as keys in a dictionary or stored inside a `set`.
```python
@dataclass(frozen=True)
class ImmutableConfig:
    api_url: str
    timeout: int

config = ImmutableConfig("https://api.system.com", 30)
config.timeout = 60  # 💥 CRASH! dataclasses.FrozenInstanceError
```

- **2. Built-in Sorting and Comparison (`order=True`)**
    - By default, you can check if two dataclasses are equal. By passing `order=True`, Python automatically generates comparison methods (`__lt__`, `__le__`, `__gt__`, `__ge__`). This allows you to sort collections of your data objects instantly.
```python
@dataclass(order=True)
class LogEntry:
    # Python will sort these based on attributes in the order they are defined (timestamp first)
    timestamp: float
    message: str

logs = [LogEntry(1715.2, "Error B"), LogEntry(1715.1, "Error A")]
print(sorted(logs))  # Sorts perfectly by timestamp!
```

- **3. Handling Mutable Defaults cleanly (`field(default_factory=...)`)**
    - In a standard Python class, setting a mutable object (like a list or a dictionary) as a default argument is a notorious trap because every instance ends up sharing the *exact same* list in memory. Dataclasses elegantly fix this via the `field` utility.
```python
from dataclasses import dataclass, field

@dataclass
class UserSession:
    username: str
    # Generates a brand-new, isolated list for every single instance created
    permissions: list[str] = field(default_factory=list) 
```

---

- **⚖️ When Should You Use Something Else?**
    - While dataclasses are excellent for general backend application modeling, there are two common scenarios where other utilities might serve you better:
        * **Tuples / NamedTuples:** If your data structure is completely static, tiny, and you want to be able to unpack it like a normal tuple (e.g., `x, y = coordinates`), a `namedtuple` is lighter on memory.
        * **Pydantic Models:** If your application is ingesting untrusted external data (like raw JSON payloads from an API HTTP request) and you need strict runtime data validation and parsing, **Pydantic** is the industry standard. Dataclasses check type hints for structure, but they *do not* block you from passing a string into a field marked as an integer at runtime.

- Further, dataclass has flags for:
    - **repr:** This generates a __repr__ magic function that generates a nice and readable output like Sandwich(spam=1, eggs=2) instead of something like **<__main__.Sandwich object at 0x...>**.
    - **eq:** This generates an automatic comparison method that compares two instances of Sandwich by their value when doing if **sandwich_a == sandwich_b**.
    - **order:** This generates a whole range of methods so that comparison operators such as **>=** and **<** work by comparing the output of dataclasses.astuple.
    - **unsafe_hash:** This will force the generation of a __hash__ method so that you use the **hash()** function on it. By default, a __hash__ function is only generated when all parts of the object are considered immutable. The reason for this is that **hash()** should always be consistent. If you wish to store an object in a set, it needs to have a consistent hash. Since a set uses **hash()** to decide which memory address to use, if the object changes, the set would need to move the object as well.
    - **frozen:** This will prevent changes after the instance has been created. The main use for this is to make sure the **hash()** of the object remains consistent.
    - **slots:** This automatically adds a __slots__ attribute which makes attribute access and storage faster and more efficient.

In [59]:
from typing import List

In [72]:
@dataclasses.dataclass
class Group:
    name: str
    parent: Group = None


@dataclasses.dataclass
class User:
    user_name: str
    email: str= None
    groups: list[Group]= None

In [73]:
users = Group('users')
admins = Group('admins', users)
rick = User('rick', groups=[admins])
gvr = User('gvanrossum', 'guido@python.org', [admins])

rick.groups

[Group(name='admins', parent=Group(name='users', parent=None))]

In [74]:
rick.groups[0].parent

Group(name='users', parent=None)

- In addition to demonstrating how to link separate dataclasses together, this excerpt highlights how to establish collections as fields and construct recursive structural relationships, such as a **`Group`** class referencing its own definition as a parent. These configurations are highly advantageous when mapping data directly from **databases** or **CSV** files into organized application layers. Furthermore, because dataclasses can be easily extended with custom methods, they serve as an efficient, highly readable, and customizable foundation for building complex business data models.

### **Combining multiple scopes with ChainMap**

In Python, **`ChainMap`** Introduced in **Python 3.3** (found in the standard library's `collections` module) is a powerful, highly efficient utility designed to group multiple dictionaries or mappings into a single, combined view.

Instead of merging the dictionaries together and creating a brand-new copy of the data, `ChainMap` merely stores an internal list of references to your original dictionaries. When you perform a lookup, it searches through those dictionaries sequentially from left to right until it finds the requested key.

---

- **🏎️ The Core Utility: Scoping and Overrides**
    - The absolute best use case for a `ChainMap` is managing application configurations where you have a hierarchy of default values that can be overridden by user settings or environment flags.
    - Imagine an application with three layers of configuration:
        1. **Defaults:** Hardcoded fallback values.
        2. **User Config:** Settings saved by a specific user.
        3. **CLI Arguments:** Temporary flags passed via the terminal that override everything else.

- **The Naive Way: Merging Dictionaries**
    - To combine these without `ChainMap`, you might merge them into a single dictionary using the dictionary unpacking operator (``):
```python
defaults = {"theme": "light", "port": 8080, "debug": False}
user_config = {"theme": "dark"}
cli_args = {"port": 9000}

# ❌ Creates a brand-new dictionary in memory
active_config = {**defaults, **user_config, **cli_args}
```

**The problem:** If any of the underlying configurations change dynamically later in your program's execution, `active_config` won't know about it because it is a completely static, independent copy. Furthermore, duplicating large dictionaries wastes system memory.

- **The Pythonic Way: Using `ChainMap`**
    - `ChainMap` creates a dynamic, live window over your existing structures without duplicating anything:
```python
from collections import ChainMap

defaults = {"theme": "light", "port": 8080, "debug": False}
user_config = {"theme": "dark"}
cli_args = {"port": 9000}

# Create the dynamic lookup hierarchy (searched left-to-right)
config = ChainMap(cli_args, user_config, defaults)

# 🔍 Lookups traverse the layers sequentially
print(config["port"])   # Output: 9000  (Found instantly in cli_args)
print(config["theme"])  # Output: dark  (Skipped cli_args, found in user_config)
print(config["debug"])  # Output: False (Skipped first two, found in defaults)
```

---

- **🛠️ Advanced Superpowers of ChainMap**

- **1. It is a "Live" View**
    - Because `ChainMap` stores references rather than copies, any mutations you make to the underlying dictionaries are instantly reflected inside the map block in real-time.
```python
# Change the user's preference mid-session
user_config["theme"] = "cyberpunk"

# The ChainMap instantly updates its resolution path automatically!
print(config["theme"])  # Output: cyberpunk
```

- **2. Modifying the Map Only Affects the First Layer**
    - If you write, delete, or update data directly through a `ChainMap` object, Python **exclusively targets the very first dictionary** in its chain stack. This allows you to safely experiment with local temporary changes without accidentally overwriting your global defaults.
```python
# Modify a configuration key directly on the ChainMap
config["theme"] = "high-contrast"

# The local change is pushed straight into the leftmost dictionary (cli_args)
print(cli_args["theme"])  # Output: high-contrast
print(user_config["theme"]) # Output: cyberpunk (The deeper layer remains safely untouched!)
```

- **3. Effortless Push and Pop Scoping (`.new_child()`)**
    - If you are designing a template engine, a programming language interpreter, or a complex context processor, you often need to spawn a temporary "child scope" that inherits variables from a parent scope. `ChainMap` handles this natively via `.new_child()`.
```python
base_vars = {"user": "alice", "role": "guest"}
context = ChainMap(base_vars)

# Spawn an isolated inner execution scope block
nested_context = context.new_child({"role": "administrator"})

print(nested_context["role"]) # Output: administrator (Overridden locally)
print(nested_context["user"]) # Output: alice (Inherited smoothly from parent)

# Destroy the inner scope block, reverting the environment instantly
clean_context = nested_context.parents
print(clean_context["role"])  # Output: guest (Restored completely)
```

---

- **⏳ Time and Space Complexity**
    * **Space Complexity:** $O(1)$ auxiliary space overhead. It only creates a list of object references rather than copying keys and values into a fresh memory layout.
    * **Time Complexity:**
        * **Best Case:** $O(1)$ if the key is located in the very first dictionary layer.
        * **Worst Case:** $O(k)$ where $k$ is the total number of dictionaries inside the chain. If a key doesn't exist anywhere, Python checks each layer sequentially.

In Python, **`vars()`** is a built-in function that returns the **`__dict__`** attribute of a given object.

The `__dict__` attribute is the underlying dictionary that Python uses to store an object's writable namespace attributes. In short, `vars()` exposes the hidden "engine room" of an object, allowing you to view and manipulate its variables as a standard Python dictionary.

---

- **🛠️ The Two Modes of `vars()`**
    - The behavior of `vars()` changes depending on whether you pass an argument to it or leave it empty.

- **1. With an Argument: Inspecting Objects**
    - When you pass an object (like a class instance or a module) into `vars(obj)`, it exposes that specific object's namespace attribute dictionary.
```python
class Project:
    def __init__(self, name: str, budget: int):
        self.name = name
        self.budget = budget

# Create an instance
web_app = Project("E-Commerce Portal", 50000)

# Inspect the object's namespace dictionary
print(vars(web_app))
# Output: {'name': 'E-Commerce Portal', 'budget': 50000}
```

- **2. Without an Argument: Inspecting the Local Scope**
    - If you call `vars()` with no arguments inside a function, it behaves exactly like the built-in `locals()` function—returning a dictionary representing the current local namespace.
```python
def calculate_metrics():
    x = 10
    y = 20
    # Capture the active local namespace environment
    print(vars())  

calculate_metrics()  # Output: {'x': 10, 'y': 20}
```

---

- **🚀 The Core Utilities of `vars()`**

- **1. Dynamic String Formatting (`vars()`)**
    - One of the most practical, elegant tricks with `vars()` is combining it with dictionary unpacking (``) to clean up complex string formatting. Instead of manually passing every attribute into a string or using long f-strings, you can pass the object's namespace dictionary directly.
```python
class Employee:
    def __init__(self, first_name: str, role: str, department: str):
        self.first_name = first_name
        self.role = role
        self.department = department

staff = Employee("Alice", "Lead Engineer", "Infrastructure")

# Clean, decoupled string serialization
message = "{first_name} works as a {role} in the {department} division.".format(**vars(staff))
print(message)
# Output: Alice works as a Lead Engineer in the Infrastructure division.
```

- **2. Converting Custom Objects to JSON/Dictionaries**
    - When building REST APIs or serialization layers, you frequently need to convert custom class instances into raw dictionaries so they can be converted to JSON strings. `vars()` handles this transformation natively.
```python
import json

class Product:
    def __init__(self, sku: str, price: float):
        self.sku = sku
        self.price = price

gadget = Product("SKU-9981", 299.99)

# Transform the custom class instance into a serialized JSON string
json_payload = json.dumps(vars(gadget))
print(json_payload)  # Output: {"sku": "SKU-9981", "price": 299.99}
```

- **3. Dynamic Attribute Modification**
    - Because `vars(obj)` returns the *actual* dictionary reference powering the object rather than a copied snapshot, modifying the dictionary directly changes the real-world attributes on that object in real-time.
```python
class Configuration:
    def __init__(self):
        self.timeout = 30

config = Configuration()
config_namespace = vars(config)

# Inject/modify attributes dynamically through the dict view
config_namespace["timeout"] = 60
config_namespace["debug_mode"] = True

# The physical object attributes are instantly updated!
print(config.timeout)     # Output: 60
print(config.debug_mode)  # Output: True
```

---

- **⚠️ Important Limitations and Pitfalls**

- **1. Objects without a `__dict__` will Crash**
    - Not all objects use dictionaries to store their attributes. For instance, objects that use **`__slots__`** (an optimization trick to save RAM) or built-in types like integers, strings, and lists do not have a `__dict__`. Passing them into `vars()` will trigger an immediate crash.
```python
# ❌ Built-in sequences do not track metadata using namespace dicts
vars([1, 2, 3])  # 💥 CRASH! TypeError: vars() argument must have __dict__ attribute
```

- **2. Avoid modifying `vars()` without arguments**
    - While modifying `vars(obj)` works perfectly for class instances, trying to modify `vars()` when it represents the **local scope** of a function will result in erratic behavior. Python optimizes local function scopes using a fast array mechanism under the hood; changes made to the local dictionary often won't sync back to the actual local variables.

In [75]:
import builtins

In [79]:
builtins_vars = vars(builtins)

key = 'something to search for'

if key in locals():
    value = locals()[key]
elif key in globals():
    value = globals()[key]
elif key in builtins_vars:
    value = builtins_vars[key]
else:
    raise NameError(f'name {key!r} is not defined')

NameError: name 'something to search for' is not defined

In [80]:
mappings = locals(), globals(), vars(builtins)

for mapping in mappings:
    if key in mapping:
        value = mapping[key]
        break
else:
    raise NameError(f'name {key!r} is not defined')

NameError: name 'something to search for' is not defined

In [81]:
from collections import ChainMap

In [82]:
mappings = ChainMap(locals(), globals(), vars(builtins))

mappings[key]

KeyError: 'something to search for'

In [1]:
import json
import pathlib
import argparse
from collections import ChainMap

In [7]:
DEFAULT = dict(verbosity=1)

config_file = pathlib.Path('config.json')
if config_file.exists():
    config = json.load(config_file.open())
else:
    config = dict()

parser =argparse.ArgumentParser()
parser.add_argument('-v', 
                    '--verbose', 
                    action='count', 
                    dest='verbosity')

args, _ = parser.parse_known_args()
defined_args = {f: v for k, v in vars(args).items() if v}
combined = ChainMap(defined_args, config, DEFAULT)

combined['verbosity']

1

In [8]:
args, _ = parser.parse_known_args(['-vv'])
defined_args = {k: v for k, v in vars(args).items() if v}
combined = ChainMap(defined_args, config, DEFAULT)

combined['verbosity']

2

In [9]:
args

Namespace(verbosity=2)

### **Default dictionary values using defaultdict**

In Python, **`defaultdict`** (found in the standard library's `collections` module) is a subclass of the built-in dictionary (`dict`). Its primary utility is to **eliminate `KeyError` crashes** when you try to access or modify a key that does not exist yet in the dictionary.

With a standard dictionary, accessing a missing key crashes your script unless you write defensive code. A `defaultdict` solves this by automatically manufacturing a default value on the fly the exact moment a missing key is requested.

---

- **🏎️ The Core Utility: Eliminating Defensive Boilerplate**
    - Imagine you want to group a list of tasks by the person assigned to them.

- **The Naive Way (Standard `dict`)**
    - If you try to append a task to a person's list before that person exists in the dictionary, Python throws a `KeyError`. You have to constantly check for the key's existence:
```python
tasks = [("Alice", "Code feature"), ("Bob", "Review PR"), ("Alice", "Fix bug")]

# Standard Dictionary
task_board = {}
for name, task in tasks:
    if name not in task_board:
        task_board[name] = []  # ⚠️ Defensive boilerplate initialization
    task_board[name].append(task)
```

- **The Clean Way (Using `defaultdict`)**
    - When you initialize a `defaultdict`, you pass it a **callable factory** (like `list`, `int`, `set`, or a custom function). If a key is missing, it calls that factory to create the starting value automatically.
```python
from collections import defaultdict

# Tell the defaultdict to automatically create a new list [] for missing keys
task_board = defaultdict(list)

for name, task in tasks:
    # No if-statements required! If 'name' isn't there, a list is born instantly.
    task_board[name].append(task)

print(dict(task_board))
# Output: {'Alice': ['Code feature', 'Fix bug'], 'Bob': ['Review PR']}
```

---

- **🛠️ Common Use Cases and Factories**
    - The data type you pass into `defaultdict()` determines what the automatic fallback value will be.

- **1. Frequency Counting with `int`**
    - Passing `int` sets the default value to `0` (since calling `int()` returns `0`). This makes it the perfect tool for counting occurrences of items.
```python
text = "apple banana apple cherry banana apple"
counter = defaultdict(int)

for word in text.split():
    counter[word] += 1  # 🔄 Automatically starts at 0, then adds 1

print(dict(counter))
# Output: {'apple': 3, 'banana': 2, 'cherry': 1}
```

- **2. Grouping Unique Values with `set`**
    - If you want to group items but ensure there are absolutely no duplicates in your collections, pass `set` as the factory (which initializes an empty `set()`).
```python
# Grouping unique error codes per module
errors = defaultdict(set)
errors["auth"].add(401)
errors["auth"].add(401)  # Duplicate ignored naturally by the set
errors["database"].add(500)

print(dict(errors))
# Output: {'auth': {401}, 'database': {500}}
```

- **3. Nested Tree Structures with Custom Functions**
    - You can pass lambda expressions or custom functions to build deeply nested architectures, such as an infinitely expanding JSON-like tree structure.
```python
# A dictionary that automatically creates another dictionary when a key is missing
def tree(): 
    return defaultdict(tree)

users = tree()
users["corporate"]["finance"]["manager"] = "Alice"
# This resolves perfectly without initializing 'corporate' or 'finance' separately!
```

---

- **⚠️ Crucial Gotchas to Keep in Mind**

- **1. The Act of Looking Up a Key Creates It**
    - Simply checking if a key exists in a `defaultdict` by printing it or referencing it **will physically write that key into memory** with its default value.
```python
metrics = defaultdict(list)

# Just checking to see if it's there...
print(metrics["missing_key"])  # Output: []

# It now physically exists inside the dictionary structure!
print(dict(metrics))  # Output: {'missing_key': []}
```

* **Solution:** If you just want to check if a key is present without accidentally creating it, use the standard `if key in my_defaultdict:` syntax.

- **2. You Must Pass the Callable, Not the Object**
    - When initializing the `defaultdict`, you must pass the name of the function/class itself (`list`), **not an executed instance** (`list()`).
```python
# ❌ INCORRECT: Crashes with a TypeError
bad_dict = defaultdict(list()) 

#  CORRECT: Pass the blueprint callable
good_dict = defaultdict(list)  
```

In [18]:
import pprint

In [19]:
nodes = [
    ('a', 'b'),
    ('a', 'c'),
    ('b', 'a'),
    ('b', 'd'),
    ('c', 'a'),
    ('d', 'a'),
    ('d', 'b'),
    ('d', 'c')
]

graph = dict()

for from_, to in nodes:
    if from_ not in graph:
        graph[from_] = []
    graph[from_].append(to)

pprint.pprint(graph)

{'a': ['b', 'c'], 'b': ['a', 'd'], 'c': ['a'], 'd': ['a', 'b', 'c']}


In [20]:
from collections import defaultdict

In [21]:
graph = defaultdict(list)

for from_, to in nodes:
    graph[from_].append(to)

pprint.pprint(graph)

defaultdict(<class 'list'>,
            {'a': ['b', 'c'],
             'b': ['a', 'd'],
             'c': ['a'],
             'd': ['a', 'b', 'c']})


In [22]:
import json

In [25]:
def tree():
    return defaultdict(tree)

colours = tree()

colours['other']['black'] = 0x000000
colours['other']['white'] = 0xFFFFFF
colours['primary']['red'] = 0xFF0000
colours['primary']['green'] = 0x00FF00
colours['primary']['blue'] = 0x0000FF
colours['secondary']['yellow'] = 0xFFFF00
colours['secondary']['aqua'] = 0x00FFFF
colours['secondary']['fuchsia'] = 0xFF00FF

print(json.dumps(colours, sort_keys=True, indent=4))

{
    "other": {
        "black": 0,
        "white": 16777215
    },
    "primary": {
        "blue": 255,
        "green": 65280,
        "red": 16711680
    },
    "secondary": {
        "aqua": 65535,
        "fuchsia": 16711935,
        "yellow": 16776960
    }
}


### **enum – A group of constants**

In Python, an **`Enum`** (short for **Enumeration**, found in the standard library's `enum` module) **introduced in Python 3.4** is a powerful tool used to define a collection of **symbolic names bound to unique, constant values**.

Its primary utility is to replace arbitrary or "magic" values (like strings or integers) with clear, structured, and unchangeable identifiers. This makes your code self-documenting, safer to refactor, and immune to typos.

---

- **🏎️ The Core Utility: Eradicating "Magic Numbers"**
    - Imagine you are writing a piece of software that processes orders, and an order can have four states: *Pending*, *Processing*, *Shipped*, or *Delivered*.

- **The Fragile Way (Using Raw Strings or Integers)**
    - Without an `Enum`, you might track the state using simple strings or integers across your system:
```python
# System tracking status with strings
def process_shipping(order):
    if order["status"] == "shipped":  # ⚠️ Easy to mistype as "shiped" or "Shipped"
        print("Sending tracking email...")
```

* **The problems:**
    * **Typos:** If someone accidentally types `"shiped"` (with one 'p') somewhere else in the codebase, Python won't throw an error, but your conditional logic will silently fail.
    * **No Code Autocomplete:** Your code editor has no idea what valid strings exist for `"status"`, so you have to constantly look up documentation or database schemas.

- **The Robust Way (Using `Enum`)**
    - An `Enum` bundles these states into a formal, unalterable namespace structural type.
```python
from enum import Enum

class OrderStatus(Enum):
    PENDING = 1
    PROCESSING = 2
    SHIPPED = 3
    DELIVERED = 4

# Usage becomes explicit and completely protected
def process_shipping(order):
    if order["status"] == OrderStatus.SHIPPED:
        print("Sending tracking email...")
```

> Now, if you mistype the status (e.g., `OrderStatus.SHIPED`), your code editor or local linter will instantly flag it as a compilation/syntax error before you ever run the script.

---

- **🛠️ Advanced Superpowers of Enums**

- **1. Immutability (Unchangeable Constants)**
    - Once defined, Enum members are completely read-only. This prevents other developers (or buggy functions) from accidentally modifying your global variables mid-session.
```python
# Try to redefine a status value at runtime
OrderStatus.PENDING = 99  # 💥 CRASH! AttributeError: Cannot reassign members.
```

- **2. Ensuring Unique Values (`@unique`)**
    - By default, multiple Enum names can point to the same value (acting as an alias). If your architecture requires that every single constant value be absolutely unique, you can enforce it using the `@unique` decorator.
```python
from enum import Enum, unique

@unique
class HTTPStatus(Enum):
    OK = 200
    SUCCESS = 200  # 💥 CRASH! ValueError: duplicate values found: SUCCESS -> OK
```

- **3. Autonumbering Values (`auto()`)**
    - If the exact underlying scalar value doesn't matter to your application logic (you just care that the states are distinct from one another), you can use `auto()` to dynamically number them.
```python
from enum import Enum, auto

class UserRole(Enum):
    GUEST = auto()      # Automatically assigned 1
    MEMBER = auto()     # Automatically assigned 2
    ADMIN = auto()      # Automatically assigned 3
```

- **4. Direct Interoperability (`IntEnum` or `StrEnum`)**
    - Standard Enums don't compare directly to strings or integers (e.g., `OrderStatus.PENDING == 1` evaluates to `False`). If you need your enums to easily mix with database types, JSON serialization, or legacy functions, you can inherit from specialized classes like `IntEnum` or `StrEnum` (introduced in Python 3.11):
```python
from enum import StrEnum

class APIEndpoint(StrEnum):
    LOGIN = "/api/v1/login"
    LOGOUT = "/api/v1/logout"

# Works seamlessly as a raw string!
print(APIEndpoint.LOGIN + "?redirect=true") 
# Output: /api/v1/login?redirect=true
```

---

- **📈 Summary of Benefits :**
    * **Domain Readability:** Replaces obscure database IDs or arbitrary status codes with human-readable text (`UserRole.ADMIN` vs. `3`).
    * **Type Hinting Integration:** You can enforce functions to accept *only* valid enum states. (e.g., `def update(status: OrderStatus):`).
    * **Clean Iteration:** You can loop over an Enum class directly to get a clean list of all possible valid options for UI dropdown menus or configuration validators.

In [42]:
from enum import Enum, StrEnum

In [29]:
class Colour(Enum):
    red= 1
    green= 2
    yello= 3

In [30]:
Colour.red

<Colour.red: 1>

In [31]:
Colour['red']

<Colour.red: 1>

In [33]:
Colour(1)

<Colour.red: 1>

In [35]:
Colour.red.name

'red'

In [36]:
Colour.red.value

1

In [37]:
isinstance(Colour.red, Colour)

True

In [39]:
Colour.red is Colour['red']

True

In [40]:
colors = dict()
colors[Colour.green] = 0x00FF00

colors

{<Colour.green: 2>: 65280}

In [41]:
class Spam(Enum):
    SPAM = 'spam'

Spam.SPAM == 'spam'

False

In [44]:
class Spam(StrEnum):
    SPAM = "spam"

Spam.SPAM == 'spam'

True

In [45]:
class Spam(str, Enum):
    SPAM = 'spam'

Spam.SPAM == 'spam'

True

- Beyond standard constants, the **`enum`** package offers specialized variants like **`enum.Flag`** and **`enum.IntFlag`** that natively support bitwise operations, making them ideal for compactly aggregating multiple distinct states or permissions using the bitwise OR **(`|`)** operator.

- Ultimately, whenever an application requires a cohesive group of related constant values, implementing an enumeration is highly recommended over raw strings or integers. Utilizing enums drastically simplifies input validation pipelines, transforming cumbersome, error-prone multi-line **`if/elif/else`** conditional chains into a clean, structured, and self-documenting architectural pattern.

### **Sorting collections using heapq**

In Python, **`heapq`** is a built-in library that provides an implementation of the **binary heap algorithm**, specifically configured as a **Min-Heap**.

Its primary utility is to efficiently manage a collection of data where you need to constantly retrieve or extract the **smallest (or largest) element** without the high performance cost of sorting the entire collection every time a new item is added.

---

- **🏎️ The Core Utility: The Priority Queue**
    - To understand why `heapq` is so useful, imagine you are building a task scheduler or a hospital emergency room queue where tasks have different priority levels (e.g., Priority 1 is critical, Priority 5 is low).

- **The Inefficient Way: Sorting an Array**
    - If you use a standard Python list, you have two choices when a new patient arrives:
        1. Append the patient to the end of the list ($O(1)$) and sort the whole list ($O(n \log n)$) to find the most critical person.
        2. Keep the list sorted dynamically by inserting the patient into the correct spot ($O(n)$ because Python must shift all subsequent items in memory).

> As your dataset grows to thousands of items, continuously sorting or shifting elements destroys your application's performance.

- **The Efficient Way: Using `heapq`**
    - A heap structures data as a balanced binary tree where the **parent node is always smaller than or equal to its child nodes**. This means the absolute smallest item in the collection is guaranteed to live at the very top (index `0`).
    - Instead of keeping everything perfectly ordered, a heap maintains a state of "partial order." This structural property yields incredibly fast operations:
        * **Inserting an item (`heappush`):** Takes only **$O(\log n)$** time.
        * **Extracting the smallest item (`heappop`):** Takes only **$O(\log n)$** time.

---

- **🛠️ Practical Code Examples**
    - The `heapq` module operates directly on standard Python lists, transforming them in-place.

- **1. Basic Min-Heap Mechanics**
```python
import heapq

# Start with a standard, unsorted list
data = [19, 3, 7, 1, 5]

# Transform the list into a heap structural layout in-place: O(n) time
heapq.heapify(data)

# The smallest item is guaranteed to be at index 0
print(data[0])  # Output: 1

# Extract the smallest item safely: O(log n)
smallest = heapq.heappop(data)
print(smallest)  # Output: 1
print(data[0])   # Output: 3 (The next smallest dynamically floated to the top)

# Push a new item onto the heap: O(log n)
heapq.heappush(data, 2)
print(data[0])   # Output: 2 (The heap rearranged itself automatically)
```

- **2. Implementing a Max-Heap (Inverting Values)**
    - Because Python’s `heapq` is strictly a Min-Heap, if your business logic requires a **Max-Heap** (where you want to constantly extract the *largest* value), the standard convention is to multiply your numerical values by `-1` before pushing them into the heap.
```python
import heapq

prices = [100, 550, 200, 450]
max_heap = []

for price in prices:
    # Invert the sign to reverse the sorting priority
    heapq.heappush(max_heap, -price)

# Pop the value and flip the sign back to positive
largest_price = -heapq.heappop(max_heap)
print(largest_price)  # Output: 550
```

- **3. Finding the Top "K" Elements Instantly**
    - If you have a massive dataset and you want to extract the top 3 largest or smallest items, `heapq` provides highly optimized convenience functions that run significantly faster than sorting the entire list.
```python
import heapq

scores = [45, 99, 12, 78, 56, 89, 23]

# Grab the 3 highest scores instantly
top_three = heapq.nlargest(3, scores)
print(top_three)  # Output: [99, 89, 78]

# Grab the 2 lowest scores instantly
bottom_two = heapq.nsmallest(2, scores)
print(bottom_two)  # Output: [12, 23]
```

---

- **⚖️ Cheat Sheet: When to use `heapq`**

| Scenario | Best Tool | Why? |
| --- | --- | --- |
| You need to sort a static list **once** and read it. | `list.sort()` | Best for batch sorting when no new items are coming in. |
| You are constantly **streaming new data** in and need the smallest/largest value at any given second. | `heapq` | Extremely lightweight; insertions and deletions are highly optimized ($O(\log n)$). |
| You need everything perfectly sorted sequentially from index `0` to `N` at all times. | `bisect` or external structures | A heap only guarantees the order of the *root element* at index `0`; the rest of the list is not sorted sequentially. |

In [46]:
import heapq

In [55]:
heap = [2, 4, 8, 3, 9, 5, 6, 7, 1]
heapq.heapify(heap)

heap

[1, 2, 5, 3, 9, 8, 6, 7, 4]

In [56]:
while heap:
    print(heapq.heappop(heap), heap)

1 [2, 3, 5, 4, 9, 8, 6, 7]
2 [3, 4, 5, 7, 9, 8, 6]
3 [4, 6, 5, 7, 9, 8]
4 [5, 6, 8, 7, 9]
5 [6, 7, 8, 9]
6 [7, 9, 8]
7 [8, 9]
8 [9]
9 []


- A crucial architectural characteristic of Python's **`heapq`** module is that it does not instantiate a unique, dedicated object type; rather, it consists of a collection of standalone utility functions designed to treat a standard, native **`list`** as a heap structure. While this implementation detail does not diminish its algorithmic utility or high-performance efficiency, it is an important structural consideration to keep in mind, as the underlying collection remains a regular Python list that can still be modified or broken by standard, non-heap list operations.

In [63]:
def heapsort(iterable):
    heap = []

    for value in iterable:
        heapq.heappush(heap, value)

    while heap:
        yield heapq.heappop(heap)

In [64]:
list(heapsort([1, 3, 5, 2, 4, 1]))

[1, 1, 2, 3, 4, 5]

- With both **`heappush`** and **`heappop`** operations executing at an efficient **$O(\log n)$** logarithmic time complexity, combining these methods sequentially across a collection of **$n$** elements yields an overall performance of **$O(n \log n)$** for the complete **`heapsort`** function.

- To maintain this speed during data insertion, the underlying **`heappush`** implementation relies on the constant-time **`list.append()`** method to place new items at the end of the array, subsequently executing index swaps to float the value into its mathematically correct heap position—thereby entirely bypassing the costly linear **$O(n)$** memory shifts typically required by standard **`list.insert()`** operations.

> The **log(n)** refers to the base 2 logarithm function. To calculate this value, the **math.log2()** function can be used. This results in an increase of 1 every time the number doubles in size. For n=2, the value of **log(n)** is 1, and consequently for **n=4** and **n=8**, the log values are 2 and 3, respectively. And **n=1024** results in a log of only 10. This means that a 32-bit number, which is **2\*\*32 = 4294967296**, has a log of 32.

In Python, the **`yield`** keyword is used to create a **generator function**. Its primary utility is to allow a function to return data **one piece at a time** instead of delivering the entire payload at once, making it the ultimate tool for **memory efficiency and handling massive streaming datasets.**

To understand its utility, it helps to contrast it directly with the standard `return` keyword.

---

- **🏎️ The Core Utility: Memory Preservation**
    - When a standard function encounters a `return` statement, it packages all the data into memory (like a list), hands it over to the caller, and **completely destroys its local state and variables.**
    - When a function uses `yield`, it sends a single value back to the caller and **pauses its execution right there**, freezing its local variables in time. The next time the caller asks for data, the function wakes up exactly where it left off and runs until it hits the next `yield`.

- **The Memory Disaster: Using `return`**
    - Imagine you need to read a massive log file containing 10 million rows to search for server errors:
```python
# ❌ Memory Hog
def read_massive_file(file_path):
    results = []
    with open(file_path, "r") as f:
        for line in f:
            results.append(line)  # Loading millions of strings into RAM!
    return results
```

> If this log file is 10 Gigabytes in size, your computer will run out of RAM and your application will crash instantly because `return` forces the entire file to sit in memory simultaneously.

- **The Memory Triumph: Using `yield`**
    - By swapping `return` for `yield`, you transform the function into a lazy iterator:
```python
#  Memory Efficient
def read_massive_file_efficiently(file_path):
    with open(file_path, "r") as f:
        for line in f:
            yield line  # Sends one line, pauses, and clears memory for the next line
```

> Because this version only holds **one line of text in memory at any given millisecond**, you can process a 100-Terabyte file on a cheap laptop using almost zero RAM.

---

- **🛠️ Practical Code Example: Inside a Loop**
    - When you call a function containing `yield`, it returns a generator object. You extract values from it using a standard `for` loop or the built-in `next()` function.
```python
def countdown(num):
    print("Starting countdown...")
    while num > 0:
        yield num
        num -= 1

# Create the generator object
timer = countdown(3) 

# Execution hasn't actually started yet!
print(timer)  # Output: <generator object countdown at 0x7f...>

# Requesting values wakes the function up sequentially
print(next(timer))  # Prints: "Starting countdown..." then returns 3
print(next(timer))  # Returns 2
print(next(timer))  # Returns 1
# Calling next(timer) again would raise a StopIteration exception, signaling completion.
```

---

- **🚀 Advanced Superpowers of `yield`**

- **1. Infinite Data Streams**
    - Because elements are generated lazily on demand, `yield` makes it incredibly simple to model theoretical systems that have no end, such as continuous data tickers, real-time sensor streams, or infinite mathematical sequences.
```python
def fibonacci_sequence():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

# This loop safely runs forever without crashing your machine's memory
for number in fibonacci_sequence():
    print(number)
    if number > 1000:
        break # Easily exit the stream whenever you choose
```

- **2. Creating State Cleanups (Context Managers)**
    - The Python standard library heavily utilizes `yield` to manage resources that require setup and teardown phases, such as database connections or temporary testing fixtures in frameworks like **pytest**.
```python
import pytest

@pytest.fixture
def database_connection():
    db = setup_live_connection()
    
    yield db  # 🚀 The test execution runs right here while the function is paused
    
    db.close() # 🧼 This line runs automatically AFTER the test finishes!
```

---

- **⚖️ When should you use `yield` vs `return`?**
    * Use **`return`** if your dataset is small, or if you absolutely require random access to the elements (e.g., you need to instantly jump to index `[50]` or sort the entries dynamically).
    * Use **`yield`** if you are processing data line-by-line (like CSV processing, database scraping, or API aggregation) and only need to iterate through the collection sequentially from start to finish.

### **Searching through sorted collections using bisect**

In Python, **`bisect`** (found in the standard library's `bisect` module) is a highly optimized utility used to interact with **sorted lists**. Its primary utility is to find the correct insertion point for an element or to insert an item into a list while **maintaining its sorted order** automatically.

Under the hood, `bisect` uses the **Binary Search algorithm**. Instead of scanning a list from start to finish, it continually splits the search space in half, making it blindingly fast compared to manual linear searching.

---

- **🏎️ The Core Utility: Massive Speedup ($O(\log n)$)**
    - To understand the utility of `bisect`, imagine you have a list of one million sorted customer IDs, and you need to insert a new ID into its correct numerical spot.

- **The Slow Way: Appending and Re-sorting**
    - If you simply append the item and sort the list again, Python has to process the entire array:
```python
# ❌ Slow and inefficient for large lists
data = [10, 20, 30, 40, 50, ...]  # 1,000,000 sorted elements
data.append(35)
data.sort()  # ⚠️ Takes O(n log n) time to re-sort the whole list
```

- **The Fast Way: Using `bisect.insort`**
    - The `bisect` module provides a function called `insort` which finds the exact right spot in logarithmic time ($O(\log n)$) and places the item directly there.
```python
import bisect

# Maintain sorted order instantly
data = [10, 20, 30, 40, 50]
bisect.insort(data, 35)

print(data)  # Output: [10, 20, 30, 35, 40, 50]
```

---

- **🛠️ The Two Main Functions: `bisect` vs `insort`**
    - The module splits its functionality into two behaviors: finding the index location, or physically inserting the data.

- **1. `bisect.bisect()` — Finding the Index Only**
    - If you don't actually want to change your list, but you need to know *where* an item belongs, use `bisect()`.
    - Because duplicate values can exist, the module offers two directions:
        * **`bisect_right()`** (default): If the element already exists, returns the index *after* (to the right of) the existing entry.
        * **`bisect_left()`**: If the element already exists, returns the index *before* (to the left of) the existing entry.

```python
import bisect

grades = [60, 70, 80, 80, 90]

# Where would an 80 go if placed to the right of duplicates?
print(bisect.bisect_right(grades, 80))  # Output: 4

# Where would an 80 go if placed to the left of duplicates?
print(bisect.bisect_left(grades, 80))   # Output: 2
```

- **2. `bisect.insort()` — Inserting the Data**
    - Similarly, `insort_left()` and `insort_right()` locate the index using binary search and then execute a standard `list.insert()` behind the scenes to place the item in memory.

---

- **🚀 Genius Use Case: Replacing Clunky `if/elif` Chains**
    - A classic, highly elegant utility of `bisect` is converting continuous numeric data into categorical "buckets" (like tax brackets, exam letter grades, or loyalty tiers).
    - Instead of writing a long, hard-to-read chain of conditional statements, you can use `bisect` to map values instantly.
```python
import bisect

def get_letter_grade(score: int) -> str:
    # Define the lower boundaries of the grade thresholds
    breakpoints = [60, 70, 80, 90]
    grade_letters = ["F", "D", "C", "B", "A"]
    
    # bisect finds where the score fits in the boundaries array
    index = bisect.bisect(breakpoints, score)
    return grade_letters[index]

# Quick Lookups
print(get_letter_grade(55))  # Output: F  (Index 0)
print(get_letter_grade(85))  # Output: B  (Index 3)
print(get_letter_grade(95))  # Output: A  (Index 4)
```

---

- **⚠️ A Critical Performance Caveat**
    - While `bisect` uses binary search to locate an index in ultra-fast **$O(\log n)$** time, physically modifying the list using `insort` still forces Python to shift elements in system memory.
        * Locating the target index = **$O(\log n)$**
        * Inserting the item into a standard Python list = **$O(n)$**

> Therefore, if your program requires millions of continuous insertions on a constantly shifting array, a standard Python list using **`bisect.insort`** might still slow down. In those specific architectural cases, an advanced data structure like a **B-Tree** or a specialized library like `sortedcontainers` would serve you better.

In [65]:
import bisect

In [67]:
sorted_list = []

bisect.insort(sorted_list, 5) # O(n) = 1
bisect.insort(sorted_list, 3) # O(n) = 2
bisect.insort(sorted_list, 7) # O(n) = 3
bisect.insort(sorted_list, 9) # O(n) = 4
bisect.insort(sorted_list, 2) # O(n) = 5
bisect.insort(sorted_list, 5) # O(n) = 6

sorted_list

[2, 3, 5, 5, 7, 9]

- While the performance divergence between **`bisect`** insertion and global list sorting is negligible for minor datasets, the operational overhead scales aggressively as the volume of inputs grows. For instance, inserting a tiny array of $n=4$ items requires roughly 12 operations for a standard sort compared to 10 operations for a **`bisect`** approach, making the latter marginally faster.

- However, scaling the payload up to 1,000 items highlights a stark algorithmic shift: the sequential **`bisect`** insertion method requires only about 10,966 total operations **($1000 + 1000 \cdot \log(1000)$)**, whereas appending items individually and sorting manually explodes to an inefficient 500,500 operations based on the arithmetic progression formula **$\frac{n \cdot (n + 1)}{2}$**. Consequently, developers must exercise extreme caution when handling large-scale data insertion pipelines, as selecting the incorrect sorting architecture can lead to massive runtime bottlenecks.

In [68]:
sorted_list = [1, 3, 5]

def contains(sorted_list, value):
    for item in sorted_list:
        if item > value:
            break
        elif item == value:
            return True

    return False

In [70]:
contains(sorted_list, 3)

True

In [71]:
contains(sorted_list, 4)

False

In [72]:
contains(sorted_list, 5)

True

In [79]:
sorted_list = [1, 3, 5]

def contains(sorted_list, value):
    i = bisect.bisect_left(sorted_list, value)
    return i < len(sorted_list) and sorted_list[i] == value

In [80]:
contains(sorted_list, 3)

True

In [81]:
contains(sorted_list, 4)

False

In [82]:
contains(sorted_list, 5)

True

In [90]:
class SortedList:
    def __init__(self, *values):
        self._list = sorted(values)

    def index(self, value):
        i = bisect.bisect_left(self._list, value)
        if i < len(self._list) and self._list[i] == value:
            return index

    
    def delete(self, value):
        del self._list[self.index(value)]


    def add(self, value):
        bisect.insort(self._list, value)


    def __iter__(self):
        for value in self._list:
            yield value


    def __exists__(self, value):
        return self.index(value) is not None

In [91]:
sorted_list = SortedList(1, 3, 6, 2)

In [92]:
3 in sorted_list

True

In [93]:
5 in sorted_list

False

In [94]:
sorted_list.add(5)

5 in sorted_list

True

In [95]:
list(sorted_list)

[1, 2, 3, 5, 6]

### **Global instances using Borg or Singleton patterns**

The **Singleton pattern** is a classic creational design pattern used to guarantee that a class has **only one single instance** in existence across your entire application lifecycle, while providing a global point of access to that specific instance.

It is typically used to manage shared global resources—such as a centralized database connection pool, a configuration manager, or an application-wide logging utility—where having multiple instances would lead to memory waste, file corruption, or conflicting states.

---

- **🏎️ The Core Mechanism: Controlling Object Creation**
    - In standard object-oriented programming, calling a class constructor like `DatabaseConnection()` creates a brand-new object in memory with a unique address every single time.
    - The Singleton pattern intercepts this process. It checks if an instance of the class has already been created:
        * If **no**, it creates the instance and saves a reference to it.
        * If **yes**, it bypasses object creation entirely and simply hands you the reference to the existing instance.

---

- **🛠️ Implementing Singleton in Python**
    - Because Python handles object creation using the magic method `__new__()` (which physically allocates memory for an object before `__init__()` initializes it), we can implement a clean, robust Singleton by overriding this method.
    - **The Code :**
```python
class DatabaseConnection:
    # 🔒 Private class variable to store our single global instance
    _instance = None

    def __new__(cls, *args, **kwargs):
        # If an instance doesn't exist yet, build one and cache it
        if cls._instance is None:
            print("🛢️ Establishing core database connection pool...")
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, db_url: str = "localhost:5432"):
        # Safeguard to prevent re-initialization overrides
        if not hasattr(self, "_initialized"):
            self.db_url = db_url
            self._initialized = True
```

- **Watching the Singleton Behavior**
    - Let's see what happens when separate parts of an application try to spin up "new" connections:
```python
# Part of the app initializes the database
connection1 = DatabaseConnection("production-db:5432")
print(connection1.db_url)  # Output: production-db:5432

# Another module tries to initialize a completely different connection address
connection2 = DatabaseConnection("staging-db:5432")
print(connection2.db_url)  # Output: production-db:5432 (The update was ignored!)

# 🔍 The Proof: Both variables point to the EXACT same memory address
print(connection1 is connection2)  # Output: True
```

---

- **🚀 Common Use Cases**
    - Singletons are highly effective when structural consistency and resource conservation are critical:
        * **Hardware Drivers:** You only have one physical printer or network card; multiple driver instances would corrupt data streams.
        * **Configuration Files:** Reading a large `.yaml` or `.env` configuration file once and caching it globally so your app isn't continuously slamming the disk read/write heads.
        * **Thread Pools:** Managing an exact number of active worker threads globally to avoid locking up CPU cores.

---

- **⚠️ The Dark Side of Singletons (Why developers avoid them)**
    - While useful, the Singleton pattern is often considered an **anti-pattern** if overused, due to several architectural downsides:

- **1. It is Globally Shared State**
    - Singletons hide dependencies inside your code instead of making them explicit. If a small function halfway across your application mutates an attribute on a Singleton, it can cause unpredictable, hard-to-track side effects in a completely unrelated module.

- **2. It Destroys Unit Testing**
    - Unit tests should be perfectly isolated from one another. Because a Singleton persists across the entire runtime of your test runner, state changes made by Test A will bleed directly into Test B, resulting in erratic, brittle test suites that fail unpredictably depending on the execution order.

- **3. Thread Safety Issues**
    - In multi-threaded environments (like a web server handling concurrent requests), if two threads hit the `if cls._instance is None:` check at the exact same millisecond, they can accidentally spawn *two* instances, defeating the pattern entirely unless thread locks (`threading.Lock()`) are explicitly implemented.

---

- **⚖️ Singleton vs. The Borg Pattern**
    - If you are looking for alternatives to a global variable, Python developers often choose between these two approaches:
        * **Singleton:** Restricts the system to **one unique object address** in memory.
        * **Borg (Monostate):** Allows you to create **multiple unique objects**, but forces all of them to share the exact same underlying state dictionary (`__dict__`). It achieves the same functional goal but plays nicer with object inheritance.

In [19]:
class Singleton:
    def __new__(cls):
        if not hasattr(cls, '_instance'):
            cls._instance = super(Singleton, cls).__new__(cls)

        return cls._instance

class SubSingleton(Singleton):
    pass

In [21]:
a = Singleton()
b = Singleton()
c = SubSingleton()

a.a_property = 123
b.a_property, c.a_property

(123, 123)

In Python, **`super()`** is a built-in function used to gain access to inherited methods from a parent or sibling class. Its primary utility is to allow a subclass to extend or customize the behavior of a parent class without having to hardcode the parent class's name or completely rewrite its logic from scratch.

While it is most frequently used to chain constructors (`__init__`) together, its true power lies in its ability to cleanly handle complex **multiple inheritance** architectures.

---

- **🏎️ The Core Utility: Extending Rather Than Replacing**
    - Imagine you are building a game and you have a base `Enemy` class. You want to create a specialized `Boss` class that does everything a normal enemy does, but with extra health and a unique defensive shield.

- **The Hardcoded Way (Avoid This)**
    - You could manually call the parent class by its explicit name:
```python
class Enemy:
    def __init__(self, name: str):
        self.name = name
        self.health = 100

class Boss(Enemy):
    def __init__(self, name: str, shield: int):
        # ⚠️ Hardcoded parent name
        Enemy.__init__(self, name) 
        self.health = 500  # Override health
        self.shield = shield
```

**The problem:** If you ever decide to rename `Enemy` to `Character`, or change your inheritance hierarchy so that `Boss` inherits from a different class, you have to hunt down and manually change every single explicit `Enemy.__init__` call across your codebase.

- **The Flexible Way (Using `super()`)**
    - By using `super()`, Python automatically handles finding the correct parent class for you:
```python
class Boss(Enemy):
    def __init__(self, name: str, shield: int):
        # 🚀 Dynamically locate the parent class and execute its constructor
        super().__init__(name) 
        self.health = 500  
        self.shield = shield
```

> This decouples your subclass from the parent's explicit name, making your code significantly easier to maintain and refactor.

---

- **🚀 The Advanced Superpower: Solving Multiple Inheritance**
    - In languages that support **multiple inheritance** (where a single subclass can inherit from two or more parent classes), a famous structural dilemma arises known as the **Diamond Problem**.

- **The Diamond Problem Scenario**
    - Imagine you have a base class `A`, two child classes `B` and `C` that inherit from `A`, and a final subclass `D` that inherits from both `B` and `C`.
    - If you try to call a method on `D`, and you hardcode the parent calls manually, methods in class `A` will end up being executed **twice**, which can corrupt data or waste processing cycles.

- **How `super()` Saves the Day: The MRO**
    - Python solves this cleanly using `super()` combined with an algorithm called **MRO (Method Resolution Order)**. Every class in Python has an underlying sequence mapping that dictates the exact linear path Python will follow when looking for methods.
    - When you call `super()`, Python doesn't just look at the immediate parent—it consults the MRO list to find the *next class in line*, ensuring that every single class in the inheritance structure is visited **exactly once**.
```python
class A:
    def process(self):
        print("Executing A")

class B(A):
    def process(self):
        print("Executing B")
        super().process() # Passes control to the next class in the MRO

class C(A):
    def process(self):
        print("Executing C")
        super().process() # Passes control to the next class in the MRO

class D(B, C):
    def process(self):
        print("Executing D")
        super().process()

# Initialize the subclass
obj = D()
obj.process()
```

- **The Output Order**
    - If you run the code above, look at how beautifully Python coordinates the execution flow:
```text
Executing D
Executing B
Executing C
Executing A
```

> Notice how control flows smoothly through `D -> B -> C -> A`. Even though `B` doesn't explicitly know that `C` exists, `super()` inside of class `B` successfully hands off execution to `C` because it follows the linear MRO chain perfectly! You can inspect this path at any time by printing `D.__mro__`.

---

- **⚖️ Golden Rules for Using `super()` :**
    1. **Don't skip arguments:** When using `super().__init__()`, make sure you pass all the arguments that the parent class's constructor expects.
    2. **Be consistent:** If you are designing a deep class hierarchy, ensure *all* sibling and parent classes utilize `super()` inside their corresponding methods. If one class breaks the chain by hardcoding a manual call or omitting `super()`, the entire MRO pipeline can come to an abrupt halt.

The **Borg pattern** (also known as the **Monostate pattern**) is a design pattern in Python used to ensure that **all instances of a class share the exact same state (data)**, even though they remain distinct, separate objects in memory.

Popularized by Python core contributor Alex Martelli, it serves as a highly Pythonic alternative to the classic **Singleton pattern**. While a Singleton forcefully restricts a class from creating more than one physical object instance, the Borg pattern says: *"Go ahead and create as many instances as you want, but they will all share the same brain."*

---

- **🏎️ The Core Utility: Why Choose Borg Over Singleton?**
    - The classic Singleton pattern is often criticized because it fights against the natural object-oriented behavior of Python. It forces you to override creation logic (`__new__`) to intercept constructor calls and return the exact same memory address every time.
    - The Borg pattern embraces Python's underlying architecture instead. In Python, an object’s attributes are stored internally in a standard dictionary called `__dict__`. The Borg pattern works by explicitly overriding class mechanics so that **every new instance points to the exact same dictionary reference**.

- **The Code Implementation**
    - Implementing the Borg pattern in Python is incredibly simple and elegant:
```python
class Borg:
    # 🧠 The shared global state dictionary
    _shared_state = {}

    def __init__(self):
        # Explicitly force this instance's dictionary to point to the shared state
        self.__dict__ = self._shared_state

# --- Concrete Example ---

class ApplicationConfig(Borg):
    def __init__(self, theme: str = "light"):
        super().__init__()
        # If the shared state doesn't have an established theme yet, set a fallback
        if "theme" not in self:
            self.theme = theme
```

---

- **🛠️ Watching Borg in Action**
    - Let's look at how this behaves in a real script. Notice how creating "new" objects dynamically synchronizes their data automatically:
```python
# Create the first instance
config1 = ApplicationConfig(theme="dark")
print(config1.theme)  # Output: dark

# Create a completely separate instance later in the application
config2 = ApplicationConfig()
print(config2.theme)  # Output: dark (It inherited the shared state instantly!)

# Modifying config2 dynamically changes config1!
config2.theme = "cyberpunk"
print(config1.theme)  # Output: cyberpunk

# 🔍 The Proof: They are distinct objects, but share the same state dict
print(config1 is config2)           # Output: False (They are NOT the same object in memory!)
print(config1.__dict__ is config2.__dict__) # Output: True  (They share the exact same dictionary!)
```

---

- **🚀 Key Advantages of the Borg Pattern**

- **1. Robust Inheritance (Subclassing Works Natively)**
    - The biggest flaw of the traditional Singleton pattern in Python is that subclassing a Singleton class frequently breaks it, as the child class shares the creation hook and accidentally overrides the parent instance.
    - With Borg, subclassing is clean and elegant. A subclass can choose to inherit the global parent state, or seamlessly isolate its own state by defining its own dictionary block:
```python
class SpecializedConfig(Borg):
    # Overriding this isolates SpecializedConfig from the global ApplicationConfig state
    _shared_state = {} 
```

- **2. Predictable Behavior**
    - Because Borg instances are normal objects that happen to look at a shared data pool, they behave exactly like standard Python classes. They support native polymorphism, can be instantiated normally without special accessors like `getInstance()`, and work perfectly with standard testing tools and frameworks.

---

- **⚖️ When Should You Use It?**
    - The Borg pattern is exceptionally useful for centralized service layers that manage global state across an application ecosystem:
        * **Configuration Management:** Reading settings from a file once and making them globally accessible.
        * **Database Connection Pools:** Managing active connections without passing a connection object to every single function.
        * **Global Logger State:** Storing logging levels or active stream handlers across disparate modules.

In [16]:
class Borg:
    _shared_state = {}
    def __init__(self):
        self.__dict__ = self._shared_state

In [17]:
class SubBorg(Borg):
    pass

In [18]:
a = Borg()
b = Borg()

a.a_theme = 'dark'
b.a_theme

'dark'

> While both design patterns aim to centralize state access, they achieve it through completely different structural mechanisms: the **Borg pattern** allows for the creation of multiple unique object instances but forces them to share a single internal "brain" by explicitly overriding each instance's **`__dict__`** state attribute, whereas the **Singleton pattern** restricts object creation entirely by overriding the class's allocation phase via the **`__new__`** method (rather than the initialization phase of `__init__`) to ensure the application only ever references a single, unique memory address.

### **No need for getters and setters with properties**

In Python, the **`@property`** decorator is a built-in utility used to define **getters, setters, and deleters** for class attributes. Its primary utility is to let you expose class methods as if they were standard public variables (attributes).

This allows you to execute custom backend logic—like data validation, dynamic calculations, or logging—behind the scenes **without changing how external users interact with your class.**

---

- **🏎️ The Core Utility: Protecting the Interface**
    - To understand why `@property` is indispensable, imagine you are building a `Wallet` class that tracks a user's cash balance.

- **The Problem with Public Attributes**
    - If you expose the balance as a normal attribute, anyone using your class can accidentally overwrite it with invalid data:

```python
class WalletNaive:
    def __init__(self, cash: float):
        self.cash = cash

wallet = WalletNaive(100.0)
wallet.cash = -5000.0  # ❌ Invalid! A wallet cannot contain negative money, but Python allows it.
```

- **The Java Way (Clunky Getters and Setters)**
    - To fix this, you might write explicit wrapper methods, a pattern common in languages like Java:

```python
class WalletJavaStyle:
    def __init__(self, cash: float):
        self.set_cash(cash)

    def get_cash(self):
        return self._cash

    def set_cash(self, value):
        if value < 0:
            raise ValueError("Cash cannot be negative!")
        self._cash = value
```

**The Catch:** This completely breaks your public interface. Anyone who was previously reading data using `wallet.cash` now has to rewrite their code to use a function call: `wallet.get_cash()`.

- **The Pythonic Way (Using `@property`)**
    - The `@property` decorator gives you the safety of methods with the clean syntax of raw variables.
```python
class Wallet:
    def __init__(self, cash: float):
        self.cash = cash  # This automatically triggers the setter below!

    @property
    def cash(self) -> float:
        """The Getter: Runs automatically when someone types `wallet.cash`"""
        print("🔍 Checking balance...")
        return self._cash

    @cash.setter
    def cash(self, value: float):
        """The Setter: Runs automatically when someone types `wallet.cash = value`"""
        if value < 0:
            raise ValueError("Cash cannot be negative!")
        self._cash = value
```

- Look at how elegant the external usage becomes. It feels like interacting with a standard variable, but your data is completely secure:
```python
wallet = Wallet(100.0)

# Reading data executes the getter method transparently
print(wallet.cash)  # Prints "🔍 Checking balance..." then 100.0

# Writing data executes the setter method transparently
wallet.cash = 250.0  # Works perfectly

# Malicious/buggy changes are blocked instantly!
wallet.cash = -50.0  # 💥 CRASH! ValueError: Cash cannot be negative!
```

---

- **🚀 Key Advantages of `@property`**

- **1. On-the-Fly Dynamic Calculations**
    - Properties are excellent for values that depend on other attributes. Instead of manually updating a composite variable every time a base variable changes, a property calculates it dynamically on demand.
```python
class Circle:
    def __init__(self, radius: float):
        self.radius = radius

    @property
    def area(self) -> float:
        # Automatically updates if self.radius changes!
        return 3.14159 * (self.radius ** 2)

circle = Circle(5)
print(circle.area)  # Output: 78.539

circle.radius = 10
print(circle.area)  # Output: 314.159
```

- **2. Creating Read-Only Attributes**
    - If you want to expose a variable that external scripts can look at but are absolutely forbidden from modifying, simply define a getter property **without** creating a corresponding `.setter`.
```python
class User:
    def __init__(self, username: str):
        self._username = username

    @property
    def username(self) -> str:
        return self._username

account = User("cyber_ninja")
print(account.username)  # Output: cyber_ninja

# Attempting to overwrite a read-only property throws an error
account.username = "hacker"  # 💥 CRASH! AttributeError: property 'username' has no setter
```

- **3. Safe API Refactoring (Backward Compatibility)**
    - If you design a class with a public attribute like `self.email`, and a year later your team decides you need to add email syntax validation, you don't have to break your company's entire codebase. You can seamlessly convert `email` into a `@property`. The external systems can keep typing `obj.email = ...` exactly like they always have, while your new validation logic handles the incoming data smoothly under the hood.

In [44]:
class Sandwish:
    def __init__(self, spam):
        self.spam = spam

    
    @property
    def spam(self):
        return self._spam


    @spam.getter
    def spam(self):
        return self._spam

    
    @spam.setter
    def spam(self, value):
        self._spam = value

        if self._spam >= 5:
            print("You must are hungry")

    
    @spam.deleter
    def spam(self):
        self._spam = 0

In [45]:
sandwish = Sandwish(2)

In [47]:
sandwish.spam += 1

In [48]:
sandwish.spam += 2

You must are hungry


In [49]:
sandwish.spam

5

### **Dict union operators**

- Prior to **Python 3.9**, combining multiple dictionary instances required a relatively verbose and clunky approach, typically involving a combination of **`dict.copy()`** to preserve the original dataset and **`dict.update()`** to physically merge the additional keys.

- While this traditional workflow operates reliably, modern versions of the language have streamlined this process by introducing cleaner, more concise syntactic alternatives—such as the merge **(`|`)** and update **(`|=`)** operators—which significantly reduce boilerplate code and enhance readability when manipulating dictionary structures.

In [50]:
# old way
a = dict(x = 1, y = 2)
b = dict(z = 3, c = 4)

c = a.copy()
print(c)

c.update(b)
print(c)

{'x': 1, 'y': 2}
{'x': 1, 'y': 2, 'z': 3, 'c': 4}


In [51]:
# The new way
a = dict(x = 1, y = 2)
b = dict(z = 3, c = 4)

a | b

{'x': 1, 'y': 2, 'z': 3, 'c': 4}